@extends('layouts.main')
@section('content')
    <div class="bio">
        <h1>Tom Hanks</h1>
        <p>Thomas Jeffrey Hanks was born in Concord, California, to Janet Marylyn (Frager), a hospital worker, and Amos Mefford Hanks, an itinerant cook. His mother's family, originally surnamed "Fraga", was entirely Portuguese, while his father was of mostly English ancestry. Tom grew up in what he has called a "fractured" family. He moved around a great deal after his parents' divorce, living with a succession of step-families. No problems, no alcoholism - just a confused childhood. He has no acting experience in college and credits the fact that he could not get cast in a college play with actually starting his career. He went downtown, and auditioned for a community theater play, was invited by the director of that play to go to Cleveland, and there his acting career started.</p>
        <p>Ron Howard was working on Splash - Una sirena a Manhattan (1984), a fantasy-comedy about a mermaid who falls in love with a business executive. Howard considered Hanks for the role of the main character's wisecracking brother, which eventually went to John Candy. Instead, Hanks landed the lead role and the film went on to become a surprise box office success, grossing more than $69 million. After several flops and a moderate success with the comedy La retata (1987), Hanks' stature in the film industry rose. The broad success with the fantasy-comedy Big (1988) established him as a major Hollywood talent, both as a box office draw and within the film industry as an actor. For his performance in the film, Hanks earned his first Academy Award nomination as Best Actor.</p>
        <p>Hanks climbed back to the top again with his portrayal of a washed-up baseball legend turned manager in Ragazze vincenti (1992). Hanks has stated that his acting in earlier roles was not great, but that he subsequently improved. In an interview with Vanity Fair, Hanks noted his "modern era of movie making ... because enough self-discovery has gone on ... My work has become less pretentiously fake and over the top". This "modern era" began for Hanks, first with Insonnia d'amore (1993) and then with Philadelphia (1993). The former was a blockbuster success about a widower who finds true love over the radio airwaves. Richard Schickel of Time magazine called his performance "charming", and most critics agreed that Hanks' portrayal ensured him a place among the premier romantic-comedy stars of his generation.</p>
        <p>In Philadelphia, he played a gay lawyer with AIDS who sues his firm for discrimination. Hanks lost 35 pounds and thinned his hair in order to appear sickly for the role. In a review for People, Leah Rozen stated, "Above all, credit for Philadelphia's success belongs to Hanks, who makes sure that he plays a character, not a saint. He is flat-out terrific, giving a deeply felt, carefully nuanced performance that deserves an Oscar." Hanks won the 1993 Academy Award for Best Actor for his role in Philadelphia. During his acceptance speech, he revealed that his high school drama teacher Rawley Farnsworth and former classmate John Gilkerson, two people with whom he was close, were gay.</p>
        <p>Hanks followed Philadelphia with the blockbuster Forrest Gump (1994) which grossed a worldwide total of over $600 million at the box office. Hanks remarked: "When I read the script for Gump, I saw it as one of those kind of grand, hopeful movies that the audience can go to and feel ... some hope for their lot and their position in life ... I got that from the movies a hundred million times when I was a kid. I still do." Hanks won his second Best Actor Academy Award for his role in Forrest Gump, becoming only the second actor to have accomplished the feat of winning consecutive Best Actor Oscars.</p>
        <p>Hanks' next role - astronaut and commander Jim Lovell, in the docudrama Apollo 13 (1995) - reunited him with Ron Howard. Critics generally applauded the film and the performances of the entire cast, which included actors Kevin Bacon, Bill Paxton, Gary Sinise, Ed Harris, and Kathleen Quinlan. The movie also earned nine Academy Award nominations, winning two. Later that year, Hanks starred in Disney/Pixar's computer-animated film Toy Story - Il mondo dei giocattoli (1995), as the voice of Sheriff Woody. A year later, he made his directing debut with the musical comedy Music Graffiti (1996) about the rise and fall of a 1960s pop group, also playing the role of a music producer.</p>
    </div>
@endsection