@extends('layouts.main')
@section('content')
    <h1>Sean Penn</h1>
    <p>Sean Penn is a powerhouse film performer capable of intensely moving work, who has gone from strength to strength during a colourful film career, and who has drawn much media attention for his stormy private life and political viewpoints.</p>
    <p>Sean Justin Penn was born in Los Angeles, California, the second son of actress Eileen Ryan (née Annucci) and director, actor, and writer Leo Penn. His brother was actor Chris Penn. His father was from a Lithuanian Jewish/Russian Jewish family, and his mother is of half Italian and half Irish descent.</p>
    <p>Penn first appeared in roles as strong-headed or unruly youths such as the military cadet defending his academy against closure in Taps - Squilli di rivolta (1981), then as fast-talking surfer stoner Jeff Spicoli in Fuori di testa (1982).</p>
    <p>Fans and critics were enthused about his obvious talent and he next contributed a stellar performance alongside Timothy Hutton in the Cold War spy thriller Il gioco del falco (1985), followed by a teaming with icy Christopher Walken in the chilling A distanza ravvicinata (1986). The youthful Sean then paired up with his then wife, pop diva Madonna in the woeful, and painful, Shanghai Surprise (1986), which was savaged by the critics, but Sean bounced back with a great job as a hot-headed young cop in Colors - colori di guerra (1988), gave another searing performance as a US soldier in Vietnam committing atrocities in Vittime di guerra (1989) and appeared alongside Robert De Niro in the uneven comedy Non siamo angeli (1989). However, the 1990s was the decade in which Sean really got noticed by critics as a mature, versatile and accomplished actor, with a string of dynamic performances in first-class films.</p>
    <p>Almost unrecognisable with frizzy hair and thin rimmed glasses, Penn was simply brilliant as corrupt lawyer David Kleinfeld in the Brian De Palma gangster movie Carlito's Way (1993) and he was still in trouble with authority as a Death Row inmate pleading with a caring nun to save his life in Dead Man Walking - Condannato a morte (1995), for which he received his first Oscar nomination. Sean then played the brother of wealthy Michael Douglas, involving him in a mind-snapping scheme in The Game - Nessuna regola (1997) and also landed the lead role of Sgt. Eddie Walsh in the star-studded anti-war film La sottile linea rossa (1998), before finishing the 1990s playing an offbeat jazz musician (and scoring another Oscar nomination) in Accordi & disaccordi (1999).</p>
    <p>The gifted and versatile Sean had also moved into directing, with the quirky but interesting Lupo solitario (1991), about two brothers with vastly opposing views on life, and in 1995 he directed Jack Nicholson in Tre giorni per la verità (1995). Both films received overall positive reviews from critics. Moving into the new century, Sean remained busy in front of the cameras with even more outstanding work: a mentally disabled father fighting for custody of his seven-year-old daughter (and receiving a third Oscar nomination) for Mi chiamo Sam (2001); an anguished father seeking revenge for his daughter's murder in the gut-wrenching Clint Eastwood-directed Mystic River (2003) (for which he won the Oscar as Best Actor); a mortally ill college professor in 21 grammi (2003) and a possessed businessman in The Assassination (2004).</p>
    <p>Certainly Sean Penn is one of Hollywood's most controversial, progressive and gifted actors.</p>
@endsection